#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmetadata has package <name>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local name=$1
  if [ -z "$name" ]; then
    log::error "name is required"
    exit 1
  fi

  metadata::has_package $name
}

run() {
  core $@
}

run $@
